### ISSUE TITLE
Longer term TODO list

### ISSUE THREAD

**Issue by fediskhakov** [fediskhakov/MathCourse#3]
Moving the items that I have to address as we go and convert to immediate things to do (to be listed in the running TODO list)

- [ ] Convert appropriate pictures to be reproduced by python scripts. Which?
- [ ] Make sure the slides can be built to PDF through latex, and look nice. Seems to be a major task, maybe after conversion to MyST/Curvenote?
- [ ] Add a page on how to use AI
- [ ] Add material on using graphing tools like Desmos
